# Generated by Django 5.1.2 on 2024-10-26 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('issued_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('issued_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('points', models.PositiveIntegerField()),
                ('total_contents', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(blank=True, to='education.course')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='education.lecturer')),
                ('tags', models.ManyToManyField(related_name='courses', to='education.tag')),
            ],
        ),
    ]
