# Generated by Django 5.1.3 on 2024-11-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_path_course_enrolled_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="path",
            name="type",
        ),
        migrations.AddField(
            model_name="path",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="paths", to="education.course"
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="path",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="education.category",
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="job_roles",
            field=models.ManyToManyField(blank=True, to="education.jobrole"),
        ),
        migrations.AddField(
            model_name="path",
            name="specialties",
            field=models.ManyToManyField(blank=True, to="education.specialty"),
        ),
    ]
