# Generated by Django 5.1.2 on 2024-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_category_jobrole_specialty_remove_path_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
