# Generated by Django 5.1.2 on 2024-11-13 20:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_enrolled_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
