# Generated by Django 5.1.2 on 2024-11-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_usercertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='issued_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
    ]
