# Generated by Django 5.1.2 on 2024-11-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_certificate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
