# Generated by Django 5.1.2 on 2024-11-14 00:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_certificate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='user_certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=50),
        ),
    ]
