# Generated by Django 5.1.2 on 2024-11-14 00:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_usercertificate_user_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='user_certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
