# Generated by Django 5.1.2 on 2024-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentFormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Consent Form', max_length=255)),
                ('content', models.TextField(help_text='The content of the consent form shown to users. You can use HTML for formatting.')),
            ],
        ),
    ]
