# Generated by Django 5.1.2 on 2024-10-31 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_consentformcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='consent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='surveys.consentformcontent'),
        ),
    ]
