# Generated by Django 5.1.2 on 2024-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_consent_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentformcontent',
            name='title',
            field=models.CharField(default='Consent Form', max_length=1047),
        ),
    ]
